### ISSUE TITLE
Le jeu ne démarre pas lorqu'il n'y a pas de périphérique audio connecté

### ISSUE THREAD

**Issue by fligiere** [khyrthy/NUER#1]
Bonjour,

Comme dit dans le titre, **le jeu ne démarre pas lorqu'il n'y a pas de périphérique audio connecté**.
Voici une capture d'écran de la fenêtre d'erreur :
![image](https://user-images.githubusercontent.com/59921587/110232117-17cc2a00-7f1c-11eb-85cf-efb9e837cca4.png)

Ce problème avait déjà été signalé lors de la bêta

**Comment by khyrthy** [comment]
Bonjour,

Il s'agit ici d'un bug spécifique du à votre système. Un problème d'interface son... (le problème est du à l'utilisation de l'interface audio Wasapi au lieu de DirectSound)

**Comment by khyrthy** [comment]
Je vais chercher à le régler dans le prochain patch, en fin de week-end
