### ISSUE TITLE
Impossible d'accéder à la barre des tâches

### ISSUE THREAD

**Issue by fligiere** [khyrthy/NUER#2]
Bonjour,

Quand le jeu est lancé (depuis Windows), on ne peut pas accéder à la barre des tâches. Lorsqu'on se rend sur celle-ci, la souris disparait.

-label:bug

**Comment by khyrthy** [comment]
Bonjour,
Si, c'est possible, il y a juste un décalage du au redimensionnement de la fenêtre du jeu.

**Comment by fligiere** [comment]
ah oui, en effet, si on descend fort on peut accéder à la barre des tâche mais ce n'est pas très pratique.
Merci pour _votre_ réponse

**Comment by khyrthy** [comment]
Merci et désolé pour le dérangement, malheureusement à l'heure actuelle, il n'est pas possible autrement..

Merci d'avoir soumis un bug
